/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import model.Person;

/**
 *
 * @author manojreddy
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    private Person person;
    
    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        geographyDataLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        telephoneNoLabel = new javax.swing.JLabel();
        faxNoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        medicalRecordNoLabel = new javax.swing.JLabel();
        healthPlanBeneficiaryNoLabel = new javax.swing.JLabel();
        bankAccountNoLabel = new javax.swing.JLabel();
        licenseNoLabel = new javax.swing.JLabel();
        vehicleIdentifierLabel = new javax.swing.JLabel();
        geographyDataText = new javax.swing.JTextField();
        deviceIdentifierLabel = new javax.swing.JLabel();
        linkedInLabel = new javax.swing.JLabel();
        ipAddressLabel = new javax.swing.JLabel();
        biometricIdentifierLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        uniqueIdentityLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        dateOfBirthText = new javax.swing.JTextField();
        telephoneNoText = new javax.swing.JTextField();
        faxNoText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        ssnText = new javax.swing.JTextField();
        medicalRecordNoText = new javax.swing.JTextField();
        healthPlanNoText = new javax.swing.JTextField();
        bankAccountNoText = new javax.swing.JTextField();
        licenseNoText = new javax.swing.JTextField();
        vehicleIdentifiersText = new javax.swing.JTextField();
        deviceIdentifiersText = new javax.swing.JTextField();
        linkedInText = new javax.swing.JTextField();
        ipAddressText = new javax.swing.JTextField();
        biometricIdText = new javax.swing.JTextField();
        photoText = new javax.swing.JTextField();
        uniqueIdentityText = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Create Person");

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("Name :");

        geographyDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        geographyDataLabel.setText("Geography Data :");

        dateOfBirthLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateOfBirthLabel.setText("Date of Birth :");

        telephoneNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telephoneNoLabel.setText("Telephone No :");

        faxNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        faxNoLabel.setText("Fax No :");

        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("Email :");

        ssnLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ssnLabel.setText("SSN :");

        medicalRecordNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medicalRecordNoLabel.setText("Medical Record No :");

        healthPlanBeneficiaryNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        healthPlanBeneficiaryNoLabel.setText("Health Plan No :");

        bankAccountNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bankAccountNoLabel.setText("Bank Acc No :");

        licenseNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        licenseNoLabel.setText("License No :");

        vehicleIdentifierLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vehicleIdentifierLabel.setText("Vehicle Identifiers :");

        deviceIdentifierLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deviceIdentifierLabel.setText("Device Identifiers :");

        linkedInLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        linkedInLabel.setText("IP Address :");

        ipAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ipAddressLabel.setText("LinkedIn :");

        biometricIdentifierLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        biometricIdentifierLabel.setText("Photo :");

        photoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        photoLabel.setText("Biometric ID :");

        uniqueIdentityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uniqueIdentityLabel.setText("Unique Identity :");

        uniqueIdentityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniqueIdentityTextActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geographyDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telephoneNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(faxNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ssnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicalRecordNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(healthPlanBeneficiaryNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleIdentifierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(licenseNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bankAccountNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceIdentifierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ipAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linkedInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uniqueIdentityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biometricIdentifierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geographyDataText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirthText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faxNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalRecordNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(healthPlanNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankAccountNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleIdentifiersText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deviceIdentifiersText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkedInText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biometricIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uniqueIdentityText, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(saveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bankAccountNoText, biometricIdText, dateOfBirthText, deviceIdentifiersText, emailText, faxNoText, geographyDataText, healthPlanNoText, ipAddressText, licenseNoText, linkedInText, medicalRecordNoText, nameText, photoText, ssnText, telephoneNoText, uniqueIdentityText, vehicleIdentifiersText});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bankAccountNoLabel, biometricIdentifierLabel, dateOfBirthLabel, deviceIdentifierLabel, emailLabel, faxNoLabel, geographyDataLabel, healthPlanBeneficiaryNoLabel, ipAddressLabel, licenseNoLabel, linkedInLabel, medicalRecordNoLabel, nameLabel, photoLabel, ssnLabel, telephoneNoLabel, uniqueIdentityLabel, vehicleIdentifierLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geographyDataLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(geographyDataText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateOfBirthText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telephoneNoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telephoneNoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faxNoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faxNoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssnLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ssnText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicalRecordNoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medicalRecordNoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(healthPlanBeneficiaryNoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(healthPlanNoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankAccountNoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bankAccountNoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(licenseNoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(licenseNoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleIdentifierLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vehicleIdentifiersText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deviceIdentifiersText)
                    .addComponent(deviceIdentifierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(linkedInText)
                    .addComponent(ipAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ipAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkedInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(biometricIdText)
                    .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(photoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biometricIdentifierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uniqueIdentityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uniqueIdentityText))
                .addGap(18, 18, 18)
                .addComponent(saveBtn)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bankAccountNoLabel, dateOfBirthLabel, dateOfBirthText, emailLabel, faxNoLabel, faxNoText, geographyDataLabel, geographyDataText, healthPlanBeneficiaryNoLabel, licenseNoLabel, medicalRecordNoLabel, ssnLabel, telephoneNoLabel, telephoneNoText, vehicleIdentifierLabel});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nameLabel, nameText});

    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void uniqueIdentityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniqueIdentityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniqueIdentityTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankAccountNoLabel;
    private javax.swing.JTextField bankAccountNoText;
    private javax.swing.JTextField biometricIdText;
    private javax.swing.JLabel biometricIdentifierLabel;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JTextField dateOfBirthText;
    private javax.swing.JLabel deviceIdentifierLabel;
    private javax.swing.JTextField deviceIdentifiersText;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel faxNoLabel;
    private javax.swing.JTextField faxNoText;
    private javax.swing.JLabel geographyDataLabel;
    private javax.swing.JTextField geographyDataText;
    private javax.swing.JLabel healthPlanBeneficiaryNoLabel;
    private javax.swing.JTextField healthPlanNoText;
    private javax.swing.JLabel ipAddressLabel;
    private javax.swing.JTextField ipAddressText;
    private javax.swing.JLabel licenseNoLabel;
    private javax.swing.JTextField licenseNoText;
    private javax.swing.JLabel linkedInLabel;
    private javax.swing.JTextField linkedInText;
    private javax.swing.JLabel medicalRecordNoLabel;
    private javax.swing.JTextField medicalRecordNoText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField photoText;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JTextField ssnText;
    private javax.swing.JLabel telephoneNoLabel;
    private javax.swing.JTextField telephoneNoText;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel uniqueIdentityLabel;
    private javax.swing.JTextField uniqueIdentityText;
    private javax.swing.JLabel vehicleIdentifierLabel;
    private javax.swing.JTextField vehicleIdentifiersText;
    // End of variables declaration//GEN-END:variables
}
