/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarsInformation;

/**
 *
 * @author manojreddy
 */
public class EdaJPanel extends javax.swing.JPanel {

    private CarsInformation carsInformation;
    
    /**
     * Creates new form EdaJPanel
     */
    public EdaJPanel() {
        initComponents();
    }
    
    public EdaJPanel(CarsInformation carsInformation) {
        initComponents();
        this.carsInformation = carsInformation;
        populateInfo();
    }

    private void populateInfo() {
        
        DefaultTableModel manufactureModel = (DefaultTableModel) manufacturersjTable.getModel();
        manufactureModel.setRowCount(0);
        
        DefaultTableModel operatingCityModel = (DefaultTableModel) operatingCitiesjTable.getModel();
        operatingCityModel.setRowCount(0);
        
        int availableCars = 0;
        int maintainanceExpiredCars = 0;
        
        Set<String> distinctManufactures = new HashSet<>();
        Set<String> distinctCities = new HashSet<>();
        
        for(Car car:carsInformation.getCars()) {
            
            distinctManufactures.add(car.getManufacturer().name());
            distinctCities.add(car.getOperatingCity().name());
            if(car.isAvailability()){
                availableCars++;
            }
            if(car.isMaintainanceCertificateExpired()){
                maintainanceExpiredCars++;
            }
        }
        
        for(String manufacture:distinctManufactures){
            Object[] row = new Object[1];
            row[0] = manufacture;
            manufactureModel.addRow(row);
        } 
        
        for(String city:distinctCities){
            Object[] row2 = new Object[1];
            row2[0] = city;
            operatingCityModel.addRow(row2);
        }
        
        availabilityCarsCountjLabel.setText(availableCars+"");
        maintainanceExpiredCarsCountjLabel.setText(maintainanceExpiredCars+"");
        totalCarsCountjLabel.setText(carsInformation.getCars().size()+"");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manufacturersUsedjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manufacturersjTable = new javax.swing.JTable();
        operatingCitiesjLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        operatingCitiesjTable = new javax.swing.JTable();
        availabilityjLabel = new javax.swing.JLabel();
        availabilityCarsCountjLabel = new javax.swing.JLabel();
        maintainanceExpiryjLabel = new javax.swing.JLabel();
        maintainanceExpiredCarsCountjLabel = new javax.swing.JLabel();
        totalCarsjLabel = new javax.swing.JLabel();
        totalCarsCountjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        manufacturersUsedjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        manufacturersUsedjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manufacturersUsedjLabel.setText("Manufacturers");

        manufacturersjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Manufacturers"
            }
        ));
        jScrollPane1.setViewportView(manufacturersjTable);

        operatingCitiesjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        operatingCitiesjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operatingCitiesjLabel.setText("Operating Cities");

        operatingCitiesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Cities"
            }
        ));
        jScrollPane2.setViewportView(operatingCitiesjTable);

        availabilityjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        availabilityjLabel.setText("Avalibility Cars Count:");

        availabilityCarsCountjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        maintainanceExpiryjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        maintainanceExpiryjLabel.setText("MaintainanceExpired Cars Count:");

        maintainanceExpiredCarsCountjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        totalCarsjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        totalCarsjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalCarsjLabel.setText("Total Cars:");

        totalCarsCountjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(manufacturersUsedjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(operatingCitiesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(availabilityjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(availabilityCarsCountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totalCarsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalCarsCountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maintainanceExpiryjLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(maintainanceExpiredCarsCountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturersUsedjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatingCitiesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availabilityjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availabilityCarsCountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maintainanceExpiredCarsCountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maintainanceExpiryjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCarsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCarsCountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabilityCarsCountjLabel;
    private javax.swing.JLabel availabilityjLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel maintainanceExpiredCarsCountjLabel;
    private javax.swing.JLabel maintainanceExpiryjLabel;
    private javax.swing.JLabel manufacturersUsedjLabel;
    private javax.swing.JTable manufacturersjTable;
    private javax.swing.JLabel operatingCitiesjLabel;
    private javax.swing.JTable operatingCitiesjTable;
    private javax.swing.JLabel totalCarsCountjLabel;
    private javax.swing.JLabel totalCarsjLabel;
    // End of variables declaration//GEN-END:variables
}
